color0 #131313
color1 #ffb4ab
color2 #ffb59c
color3 #e7bdb0
color4 #d6c68d
color5 #ffb59c
color6 #e7bdb0
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #ffb59c
color11 #e7bdb0
color12 #d6c68d
color13 #ffb59c
color14 #e7bdb0
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #ffb59c
inactive_border_color #474747
url_color             #ffb59c
