# 下载目录
dir=/home/wuuixm/Downloads

# 启用 RPC
enable-rpc=true
rpc-listen-all=false
rpc-allow-origin-all=true
rpc-listen-port=6800

# 多线程优化
max-connection-per-server=8
split=8
min-split-size=10M

# 断点续传
continue=true

# 会话保存
input-file=/home/wuuixm/.config/aria2/aria2.session
save-session=/home/wuuixm/.config/aria2/aria2.session
save-session-interval=60

# 降低磁盘碎片
file-allocation=trunc

user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36

header=Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
header=Accept-Language: en-US,en;q=0.5
header=Connection: keep-alive
